name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm i

      - name: Lint
        run: |
          npm run lint
          DIFF_INDEX=$(git diff-index --name-only HEAD)
          if [[ ${DIFF_INDEX:0:5} == "fatal" ]]; then
            echo "There was an error with the git checkout. Can't check package-lock.json file."
            false
          fi
          if [[ $DIFF_INDEX -eq 0 ]]; then
            echo "Linting is valid"
          else
            echo "The following files have not been linted"
            echo $DIFF_INDEX
            false
          fi

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: node_modules/.bin/mocha -r ts-node/register --exit 'test/**.spec.ts'
